name: app

services:
  database:
    build:
      context: ./services/database
    container_name: database
    ports:
      - "5000:5432"
    env_file:
      - .env
    restart: unless-stopped

  event_server:
    build:
      dockerfile: ./services/event_server/Dockerfile
      context: .
    container_name: event-server
    ports:
      - "5001:5001"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - database
    
  user_server:
    build:
      dockerfile: ./services/user_server/Dockerfile
      context: .
    container_name: user-server
    ports:
      - "5003:5003"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - database
  
  frontend:
    build:
      context: ./services/frontend
    container_name: frontend
    ports:
      - "5002:5002"
    restart: unless-stopped
    depends_on:
      - event_server
      - user_server
