name: app

services:
  database:
    build:
      context: ./database
    container_name: database
    ports:
      - "5000:5432"
    env_file:
      - .env
    restart: unless-stopped

  server:
    build:
      dockerfile: ./server/Dockerfile
      context: .
    container_name: server
    ports:
      - "5001:5001"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - database
  
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5002:5002"
    restart: unless-stopped
    depends_on:
      - server
