name: app

services:
  database:
    build:
      context: ./database
    container_name: database
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./database/src/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "5001:5001"
    depends_on:
      - database
