name: app

services:
  database:
    build:
      context: ./database
    container_name: database
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always

  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "5001:5001"
    env_file:
      - .env
    restart: always
    depends_on:
      - database
  
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5002:5002"
    restart: always
    depends_on:
      - server
