CREATE DATABASE database;

CREATE USER backend WITH ENCRYPTED PASSWORD 'backend_password';

GRANT ALL PRIVILEGES ON DATABASE database TO backend;

\c database;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO backend;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO backend;
